In [7]:
import numpy as np

In [11]:
print(pd.version.version)

1.17.0


In [12]:
a = np.random.random((2,3,5))

In [13]:
print(a)

[[[0.01910079 0.34465643 0.91557472 0.29428571 0.65402217]
  [0.69738362 0.5812739  0.53137307 0.64452882 0.89751593]
  [0.22063627 0.95818954 0.86903853 0.51328683 0.56124278]]

 [[0.04590673 0.67023252 0.21115663 0.69115486 0.87878041]
  [0.9967742  0.67031878 0.89158608 0.05074504 0.23630334]
  [0.37622939 0.36070351 0.05100876 0.27445099 0.69685116]]]


In [21]:
b = np.ones((5,2,3))

In [22]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [31]:
d = ([5,2,3], [2,3,5])
np.shape(d)

(2, 3)

In [34]:
c=b.reshape(2,3,5)
print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [37]:
d =a + c
print(d)

[[[1.01910079 1.34465643 1.91557472 1.29428571 1.65402217]
  [1.69738362 1.5812739  1.53137307 1.64452882 1.89751593]
  [1.22063627 1.95818954 1.86903853 1.51328683 1.56124278]]

 [[1.04590673 1.67023252 1.21115663 1.69115486 1.87878041]
  [1.9967742  1.67031878 1.89158608 1.05074504 1.23630334]
  [1.37622939 1.36070351 1.05100876 1.27445099 1.69685116]]]


In [38]:
f = d + a
print(f)

[[[1.03820159 1.68931287 2.83114944 1.58857141 2.30804434]
  [2.39476724 2.16254781 2.06274614 2.28905764 2.79503185]
  [1.44127253 2.91637908 2.73807706 2.02657367 2.12248556]]

 [[1.09181347 2.34046504 1.42231327 2.38230971 2.75756081]
  [2.9935484  2.34063755 2.78317217 1.10149008 1.47260668]
  [1.75245877 1.72140702 1.10201752 1.54890197 2.39370232]]]


In [39]:
e = a * c
print(e)

[[[0.01910079 0.34465643 0.91557472 0.29428571 0.65402217]
  [0.69738362 0.5812739  0.53137307 0.64452882 0.89751593]
  [0.22063627 0.95818954 0.86903853 0.51328683 0.56124278]]

 [[0.04590673 0.67023252 0.21115663 0.69115486 0.87878041]
  [0.9967742  0.67031878 0.89158608 0.05074504 0.23630334]
  [0.37622939 0.36070351 0.05100876 0.27445099 0.69685116]]]


In [40]:
print(a)


[[[0.01910079 0.34465643 0.91557472 0.29428571 0.65402217]
  [0.69738362 0.5812739  0.53137307 0.64452882 0.89751593]
  [0.22063627 0.95818954 0.86903853 0.51328683 0.56124278]]

 [[0.04590673 0.67023252 0.21115663 0.69115486 0.87878041]
  [0.9967742  0.67031878 0.89158608 0.05074504 0.23630334]
  [0.37622939 0.36070351 0.05100876 0.27445099 0.69685116]]]


In [49]:
print(d.max())
print(d.min())
print(d.mean())


1.9967741980519902
1.0191007938758336
1.5268103833394666
